easy_admin:
    site_name: SurMaRoute
    design:
      menu:
        - label: 'Dashboard'
          icon : 'newspaper-o'
          children: 
            - {entity: 'Utilisateur' , icon: 'newspaper-o',label: 'Utilisateur' }
            - {entity: 'Profil' , icon: 'newspaper-o',label: 'Profil' }
            - {entity: 'Trajet' , icon: 'newspaper-o'}
            - {entity: 'Avis' , icon: 'newspaper-o' }
            - {entity: 'Commentaire' , icon: 'newspaper-o' }
            - {entity: 'Reservation' , icon: 'newspaper-o' }
            - {entity: 'Contact' , icon: 'phone'}

    entities:
        Utilisateur:
           class: App\Entity\Utilisateur
           list:
                actions: 
                 - {name: 'edit', icon: 'pencil' , label: false , css_class: 'btn btn-secondary'}   
                 - {name: 'delete', icon: 'trash' , label: false , css_class: 'btn btn-danger'}   

           form:  
              fields:
                  - {property: 'nom'}
                  - {property: 'prenom'}
                  - {property: 'date_naissance'}
                  - {property: 'sexe'}
                  - {property: 'telephone'}
                  - {property: 'photo'}
                  - {property: 'email'}
                  - {property: 'password'}


        Profil:
           class: App\Entity\Profil

        Trajet:
           class: App\Entity\Trajet

        Avis:
           class: App\Entity\Avis
           
        Commentaire:
           class: App\Entity\Commentaire
           
        Reservation:
           class: App\Entity\Reservation
           
        Contact:
           class: App\Entity\Contact
